2015726096 : main.o Init.o Thread.o Scheduler.o Handler.o Queue.o MsgQueue.o TestCase1.o TestCase2.o TestCase3.o TestCase4.o
	gcc -o 2015726096 main.o Init.o Thread.o Scheduler.o Handler.o Queue.o MsgQueue.o TestCase1.o TestCase2.o TestCase3.o TestCase4.o -w
main.o : main.c
	gcc -c -o main.o main.c -w
Init.o : Init.c
	gcc -c -o Init.o Init.c -w
Thread.o : Thread.c
	gcc -c -o Thread.o Thread.c -w
Scheduler.o : Scheduler.c	
	gcc -c -o Scheduler.o Scheduler.c -w
Handler.o : Handler.c
	gcc -c -o Handler.o Handler.c -w
Queue.o : Queue.c
	gcc -c -o Queue.o Queue.c -w
MsgQueue.o : MsgQueue.c
	gcc -c -o MsgQueue.o MsgQueue.c -w
TestCase1.o : TestCase1.o
	gcc -c -o TestCase1.o TestCase1.c -w
TestCase2.o : TestCase2.o
	gcc -c -o TestCase2.o TestCase2.c -w
TestCase3.o : TestCase3.o
	gcc -c -o TestCase3.o TestCase3.c -w
TestCase4.o : TestCase4.o
	gcc -c -o TestCase4.o TestCase4.c -w
clean :
	rm *.o 2015726096
